[project]
name = "polarslake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deltalake==0.14",
    "polars==0.19.17",
    "pyarrow==14.0.1",
    "pandas==2.1.3"
]
